<?php 
class LocationSchema extends CakeSchema {
	private $countries = array(
		array("AF","Afghanistan"),
		array("AL","Albania"),
		array("DZ","Algeria"),
		array("AS","American Samoa"),
		array("AD","Andorra"),
		array("AO","Angola"),
		array("AI","Anguilla"),
		array("AQ","Antarctica"),
		array("AG","Antigua and Barbuda"),
		array("AR","Argentina"),
		array("AM","Armenia"),
		array("AW","Aruba"),
		array("AU","Australia"),
		array("AT","Austria"),
		array("AZ","Azerbaijan"),
		array("BS","Bahamas"),
		array("BH","Bahrain"),
		array("BD","Bangladesh"),
		array("BB","Barbados"),
		array("BY","Belarus"),
		array("BE","Belgium"),
		array("BZ","Belize"),
		array("BJ","Benin"),
		array("BM","Bermuda"),
		array("BT","Bhutan"),
		array("BO","Bolivia"),
		array("BA","Bosnia and Herzegovina"),
		array("BW","Botswana"),
		array("BV","Bouvet Island"),
		array("BR","Brazil"),
		array("IO","British Indian Ocean Territory"),
		array("BN","Brunei Darussalam"),
		array("BG","Bulgaria"),
		array("BF","Burkina Faso"),
		array("BI","Burundi"),
		array("KH","Cambodia"),
		array("CM","Cameroon"),
		array("CA","Canada"),
		array("CV","Cape Verde"),
		array("KY","Cayman Islands"),
		array("CF","Central African Republic"),
		array("TD","Chad"),
		array("CL","Chile"),
		array("CN","China"),
		array("CX","Christmas Island"),
		array("CC","Cocos (Keeling Islands)"),
		array("CO","Colombia"),
		array("KM","Comoros"),
		array("CG","Congo"),
		array("CK","Cook Islands"),
		array("CR","Costa Rica"),
		array("CI","Cote D'Ivoire (Ivory Coast)"),
		array("HR","Croatia (Hrvatska)"),
		array("CU","Cuba"),
		array("CY","Cyprus"),
		array("CZ","Czech Republic"),
		array("DK","Denmark"),
		array("DJ","Djibouti"),
		array("DM","Dominica"),
		array("DO","Dominican Republic"),
		array("TP","East Timor"),
		array("EC","Ecuador"),
		array("EG","Egypt"),
		array("SV","El Salvador"),
		array("GQ","Equatorial Guinea"),
		array("ER","Eritrea"),
		array("EE","Estonia"),
		array("ET","Ethiopia"),
		array("FK","Falkland Islands (Malvinas)"),
		array("FO","Faroe Islands"),
		array("FJ","Fiji"),
		array("FI","Finland"),
		array("FR","France"),
		array("FX","France, Metropolitan"),
		array("GF","French Guiana"),
		array("PF","French Polynesia"),
		array("TF","French Southern Territories"),
		array("GA","Gabon"),
		array("GM","Gambia"),
		array("GE","Georgia"),
		array("DE","Germany"),
		array("GH","Ghana"),
		array("GI","Gibraltar"),
		array("GR","Greece"),
		array("GL","Greenland"),
		array("GD","Grenada"),
		array("GP","Guadeloupe"),
		array("GU","Guam"),
		array("GT","Guatemala"),
		array("GN","Guinea"),
		array("GW","Guinea-Bissau"),
		array("GY","Guyana"),
		array("HT","Haiti"),
		array("HM","Heard and McDonald Islands"),
		array("HN","Honduras"),
		array("HK","Hong Kong"),
		array("HU","Hungary"),
		array("IS","Iceland"),
		array("IN","India"),
		array("ID","Indonesia"),
		array("IR","Iran"),
		array("IQ","Iraq"),
		array("IE","Ireland"),
		array("IL","Israel"),
		array("IT","Italy"),
		array("JM","Jamaica"),
		array("JP","Japan"),
		array("JO","Jordan"),
		array("KZ","Kazakhstan"),
		array("KE","Kenya"),
		array("KI","Kiribati"),
		array("KP","Korea (North) (People's Republic)"),
		array("KR","Korea (South) (Republic)"),
		array("KW","Kuwait"),
		array("KG","Kyrgyzstan (Kyrgyz Republic)"),
		array("LA","Laos"),
		array("LV","Latvia"),
		array("LB","Lebanon"),
		array("LS","Lesotho"),
		array("LR","Liberia"),
		array("LY","Libya"),
		array("LI","Liechtenstein"),
		array("LT","Lithuania"),
		array("LU","Luxembourg"),
		array("MO","Macau"),
		array("MK","Macedonia"),
		array("MG","Madagascar"),
		array("MW","Malawi"),
		array("MY","Malaysia"),
		array("MV","Maldives"),
		array("ML","Mali"),
		array("MT","Malta"),
		array("MH","Marshall Islands"),
		array("MQ","Martinique"),
		array("MR","Mauritania"),
		array("MU","Mauritius"),
		array("YT","Mayotte"),
		array("MX","Mexico"),
		array("FM","Micronesia"),
		array("MD","Moldova"),
		array("MC","Monaco"),
		array("MN","Mongolia"),
		array("MS","Montserrat"),
		array("MA","Morocco"),
		array("MZ","Mozambique"),
		array("MM","Myanmar"),
		array("NA","Namibia"),
		array("NR","Nauru"),
		array("NP","Nepal"),
		array("NL","Netherlands"),
		array("AN","Netherlands Antilles"),
		array("NT","Neutral Zone (Saudia Arabia/Iraq)"),
		array("NC","New Caledonia"),
		array("NZ","New Zealand"),
		array("NI","Nicaragua"),
		array("NE","Niger"),
		array("NG","Nigeria"),
		array("NU","Niue"),
		array("NF","Norfolk Island"),
		array("MP","Northern Mariana Islands"),
		array("NO","Norway"),
		array("OM","Oman"),
		array("PK","Pakistan"),
		array("PW","Palau"),
		array("PA","Panama"),
		array("PG","Papua New Guinea"),
		array("PY","Paraguay"),
		array("PE","Peru"),
		array("PH","Philippines"),
		array("PN","Pitcairn"),
		array("PL","Poland"),
		array("PT","Portugal"),
		array("PR","Puerto Rico"),
		array("QA","Qatar"),
		array("RE","Reunion"),
		array("RO","Romania"),
		array("RU","Russian Federation"),
		array("RW","Rwanda"),
		array("GS","S. Georgia and S. Sandwich Isls."),
		array("KN","Saint Kitts and Nevis"),
		array("LC","Saint Lucia"),
		array("VC","Saint Vincent and The Grenadines"),
		array("WS","Samoa"),
		array("SM","San Marino"),
		array("ST","Sao Tome and Principe"),
		array("SA","Saudi Arabia"),
		array("SN","Senegal"),
		array("SC","Seychelles"),
		array("SL","Sierra Leone"),
		array("SG","Singapore"),
		array("SK","Slovakia (Slovak Republic)"),
		array("SI","Slovenia"),
		array("SB","Solomon Islands"),
		array("SO","Somalia"),
		array("ZA","South Africa"),
		array("SU","Soviet Union (former)"),
		array("ES","Spain"),
		array("LK","Sri Lanka"),
		array("SH","St. Helena"),
		array("PM","St. Pierre and Miquelon"),
		array("SD","Sudan"),
		array("SR","Suriname"),
		array("SJ","Svalbard and Jan Mayen Islands"),
		array("SZ","Swaziland"),
		array("SE","Sweden"),
		array("CH","Switzerland"),
		array("SY","Syria"),
		array("TW","Taiwan"),
		array("TJ","Tajikistan"),
		array("TZ","Tanzania"),
		array("TH","Thailand"),
		array("TG","Togo"),
		array("TK","Tokelau"),
		array("TO","Tonga"),
		array("TT","Trinidad and Tobago"),
		array("TN","Tunisia"),
		array("TR","Turkey"),
		array("TM","Turkmenistan"),
		array("TC","Turks and Caicos Islands"),
		array("TV","Tuvalu"),
		array("UG","Uganda"),
		array("UA","Ukraine"),
		array("AE","United Arab Emirates"),
		array("UK","United Kingdom (Great Britain)"),
		array("US","United States"),
		array("UY","Uruguay"),
		array("UM","US Minor Outlying Islands"),
		array("UZ","Uzbekistan"),
		array("VU","Vanuatu"),
		array("VA","Vatican City State (Holy See)"),
		array("VE","Venezuela"),
		array("VN","Viet Nam"),
		array("VG","Virgin Islands (British)"),
		array("VI","Virgin Islands (US)"),
		array("WF","Wallis and Futuna Islands"),
		array("EH","Western Sahara"),
		array("YE","Yemen"),
		array("YU","Yugoslavia"),
		array("ZR","Zaire"),
		array("ZM","Zambia"),
		array("ZW","Zimbabwe"),
		array("M","US Military Base"),
	);
	private $states = array(
		'US' => array(
			array("AK","Alaska"),
			array("AL","Alabama"),
			array("AR","Arkansas"),
			array("AZ","Arizona"),
			array("CA","California"),
			array("CO","Colorado"),
			array("CT","Connecticut"),
			array("DC","Washington, DC"),
			array("DE","Delaware"),
			array("FL","Florida"),
			array("GA","Georgia"),
			array("HI","Hawaii"),
			array("IA","Iowa"),
			array("ID","Idaho"),
			array("IL","Illinois"),
			array("IN","Indiana"),
			array("KS","Kansas"),
			array("KY","Kentucky"),
			array("LA","Louisiana"),
			array("MA","Massachusetts"),
			array("MD","Maryland"),
			array("ME","Maine"),
			array("MI","Michigan"),
			array("MN","Minnesota"),
			array("MO","Missouri"),
			array("MS","Mississippi"),
			array("MT","Montana"),
			array("NC","North Carolina"),
			array("ND","North Dakota"),
			array("NE","Nebraska"),
			array("NH","New Hampshire"),
			array("NJ","New Jersey"),
			array("NM","New Mexico"),
			array("NV","Nevada"),
			array("NY","New York"),
			array("OH","Ohio"),
			array("OK","Oklahoma"),
			array("OR","Oregon"),
			array("PA","Pennsylvania"),
			array("RI","Rhode Island"),
			array("SC","South Carolina"),
			array("SD","South Dakota"),
			array("TN","Tennessee"),
			array("TX","Texas"),
			array("UT","Utah"),
			array("VA","Virginia"),
			array("VT","Vermont"),
			array("WA","Washington"),
			array("WI","Wisconsin"),
			array("WV","West Virginia"),
			array("WY","Wyoming"),
		),
		'CA' => array(
			array("AB","Alberta"),
			array("BC","British Columbia"),
			array("MB","Manitoba"),
			array("NB","New Brunswick"),
			array("NF","Newfoundland"),
			array("NS","Nova Scotia"),
			array("NT","Northwest Territories"),
			array("NU","Nunavut"),
			array("ON","Ontario"),
			array("PE","Prince Edward Island"),
			array("PQ","Quebec"),
			array("SK","Saskatchewan"),
			array("YT","Yukon"),
		),
		'M' => array(
			array("AA","Armed Forces Americas"),
			array("AE","Armed Forces Europe"),
		)
	);

	public function before($event = array()) {
		$db = ConnectionManager::getDataSource($this->connection);
		$db->cacheSources = false;
		return true;
	}

	public function after($event = array()) {
		if (isset ($event['create'])) {
			switch ($event['create']) {
				case 'states':
					$this->insertStates();
				break;
				case 'countries':
					$this->insertCountries();
				break;
			}
		}
	}

	public $countries = array(
		'id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'key' => 'primary', 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1)
		),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	public $states = array(
		'id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'key' => 'primary', 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'country_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'lat_min' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lat_max' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lon_min' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lon_max' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1)
		),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	
	private function insertCountries() {
		$Country = ClassRegistry::init('Location.Country');
		$Country->create();
		$data = array();
		foreach ($this->countries as $country) {
			list($id, $title) = $country;
			$data[] = compact(array('id', 'title'));
	}
	
	private function insertStates() {
		$State = ClassRegistry::init('Location.State');
		$State->create();
		$data = array();
		foreach ($this->states as $country_id => $state) {
			list($id, $title) = $state;
			$data[] = compact('country_id', 'id', 'title');
		}
		return $State->saveAll($data);
	}
}
