<?php 
class LocationSchema extends CakeSchema {
	private $countryData = array(
		array("AF","Afghanistan"),
		array("AL","Albania"),
		array("DZ","Algeria"),
		array("AS","American Samoa"),
		array("AD","Andorra"),
		array("AO","Angola"),
		array("AI","Anguilla"),
		array("AQ","Antarctica"),
		array("AG","Antigua and Barbuda"),
		array("AR","Argentina"),
		array("AM","Armenia"),
		array("AW","Aruba"),
		array("AU","Australia"),
		array("AT","Austria"),
		array("AZ","Azerbaijan"),
		array("BS","Bahamas"),
		array("BH","Bahrain"),
		array("BD","Bangladesh"),
		array("BB","Barbados"),
		array("BY","Belarus"),
		array("BE","Belgium"),
		array("BZ","Belize"),
		array("BJ","Benin"),
		array("BM","Bermuda"),
		array("BT","Bhutan"),
		array("BO","Bolivia"),
		array("BA","Bosnia and Herzegovina"),
		array("BW","Botswana"),
		array("BV","Bouvet Island"),
		array("BR","Brazil"),
		array("IO","British Indian Ocean Territory"),
		array("BN","Brunei Darussalam"),
		array("BG","Bulgaria"),
		array("BF","Burkina Faso"),
		array("BI","Burundi"),
		array("KH","Cambodia"),
		array("CM","Cameroon"),
		array("CA","Canada"),
		array("CV","Cape Verde"),
		array("KY","Cayman Islands"),
		array("CF","Central African Republic"),
		array("TD","Chad"),
		array("CL","Chile"),
		array("CN","China"),
		array("CX","Christmas Island"),
		array("CC","Cocos (Keeling Islands)"),
		array("CO","Colombia"),
		array("KM","Comoros"),
		array("CG","Congo"),
		array("CK","Cook Islands"),
		array("CR","Costa Rica"),
		array("CI","Cote D'Ivoire (Ivory Coast)"),
		array("HR","Croatia (Hrvatska)"),
		array("CU","Cuba"),
		array("CY","Cyprus"),
		array("CZ","Czech Republic"),
		array("DK","Denmark"),
		array("DJ","Djibouti"),
		array("DM","Dominica"),
		array("DO","Dominican Republic"),
		array("TP","East Timor"),
		array("EC","Ecuador"),
		array("EG","Egypt"),
		array("SV","El Salvador"),
		array("GQ","Equatorial Guinea"),
		array("ER","Eritrea"),
		array("EE","Estonia"),
		array("ET","Ethiopia"),
		array("FK","Falkland Islands (Malvinas)"),
		array("FO","Faroe Islands"),
		array("FJ","Fiji"),
		array("FI","Finland"),
		array("FR","France"),
		array("FX","France, Metropolitan"),
		array("GF","French Guiana"),
		array("PF","French Polynesia"),
		array("TF","French Southern Territories"),
		array("GA","Gabon"),
		array("GM","Gambia"),
		array("GE","Georgia"),
		array("DE","Germany"),
		array("GH","Ghana"),
		array("GI","Gibraltar"),
		array("GR","Greece"),
		array("GL","Greenland"),
		array("GD","Grenada"),
		array("GP","Guadeloupe"),
		array("GU","Guam"),
		array("GT","Guatemala"),
		array("GN","Guinea"),
		array("GW","Guinea-Bissau"),
		array("GY","Guyana"),
		array("HT","Haiti"),
		array("HM","Heard and McDonald Islands"),
		array("HN","Honduras"),
		array("HK","Hong Kong"),
		array("HU","Hungary"),
		array("IS","Iceland"),
		array("IN","India"),
		array("ID","Indonesia"),
		array("IR","Iran"),
		array("IQ","Iraq"),
		array("IE","Ireland"),
		array("IL","Israel"),
		array("IT","Italy"),
		array("JM","Jamaica"),
		array("JP","Japan"),
		array("JO","Jordan"),
		array("KZ","Kazakhstan"),
		array("KE","Kenya"),
		array("KI","Kiribati"),
		array("KP","Korea (North) (People's Republic)"),
		array("KR","Korea (South) (Republic)"),
		array("KW","Kuwait"),
		array("KG","Kyrgyzstan (Kyrgyz Republic)"),
		array("LA","Laos"),
		array("LV","Latvia"),
		array("LB","Lebanon"),
		array("LS","Lesotho"),
		array("LR","Liberia"),
		array("LY","Libya"),
		array("LI","Liechtenstein"),
		array("LT","Lithuania"),
		array("LU","Luxembourg"),
		array("MO","Macau"),
		array("MK","Macedonia"),
		array("MG","Madagascar"),
		array("MW","Malawi"),
		array("MY","Malaysia"),
		array("MV","Maldives"),
		array("ML","Mali"),
		array("MT","Malta"),
		array("MH","Marshall Islands"),
		array("MQ","Martinique"),
		array("MR","Mauritania"),
		array("MU","Mauritius"),
		array("YT","Mayotte"),
		array("MX","Mexico"),
		array("FM","Micronesia"),
		array("MD","Moldova"),
		array("MC","Monaco"),
		array("MN","Mongolia"),
		array("MS","Montserrat"),
		array("MA","Morocco"),
		array("MZ","Mozambique"),
		array("MM","Myanmar"),
		array("NA","Namibia"),
		array("NR","Nauru"),
		array("NP","Nepal"),
		array("NL","Netherlands"),
		array("AN","Netherlands Antilles"),
		array("NT","Neutral Zone (Saudia Arabia/Iraq)"),
		array("NC","New Caledonia"),
		array("NZ","New Zealand"),
		array("NI","Nicaragua"),
		array("NE","Niger"),
		array("NG","Nigeria"),
		array("NU","Niue"),
		array("NF","Norfolk Island"),
		array("MP","Northern Mariana Islands"),
		array("NO","Norway"),
		array("OM","Oman"),
		array("PK","Pakistan"),
		array("PW","Palau"),
		array("PA","Panama"),
		array("PG","Papua New Guinea"),
		array("PY","Paraguay"),
		array("PE","Peru"),
		array("PH","Philippines"),
		array("PN","Pitcairn"),
		array("PL","Poland"),
		array("PT","Portugal"),
		array("PR","Puerto Rico"),
		array("QA","Qatar"),
		array("RE","Reunion"),
		array("RO","Romania"),
		array("RU","Russian Federation"),
		array("RW","Rwanda"),
		array("GS","S. Georgia and S. Sandwich Isls."),
		array("KN","Saint Kitts and Nevis"),
		array("LC","Saint Lucia"),
		array("VC","Saint Vincent and The Grenadines"),
		array("WS","Samoa"),
		array("SM","San Marino"),
		array("ST","Sao Tome and Principe"),
		array("SA","Saudi Arabia"),
		array("SN","Senegal"),
		array("SC","Seychelles"),
		array("SL","Sierra Leone"),
		array("SG","Singapore"),
		array("SK","Slovakia (Slovak Republic)"),
		array("SI","Slovenia"),
		array("SB","Solomon Islands"),
		array("SO","Somalia"),
		array("ZA","South Africa"),
		array("SU","Soviet Union (former)"),
		array("ES","Spain"),
		array("LK","Sri Lanka"),
		array("SH","St. Helena"),
		array("PM","St. Pierre and Miquelon"),
		array("SD","Sudan"),
		array("SR","Suriname"),
		array("SJ","Svalbard and Jan Mayen Islands"),
		array("SZ","Swaziland"),
		array("SE","Sweden"),
		array("CH","Switzerland"),
		array("SY","Syria"),
		array("TW","Taiwan"),
		array("TJ","Tajikistan"),
		array("TZ","Tanzania"),
		array("TH","Thailand"),
		array("TG","Togo"),
		array("TK","Tokelau"),
		array("TO","Tonga"),
		array("TT","Trinidad and Tobago"),
		array("TN","Tunisia"),
		array("TR","Turkey"),
		array("TM","Turkmenistan"),
		array("TC","Turks and Caicos Islands"),
		array("TV","Tuvalu"),
		array("UG","Uganda"),
		array("UA","Ukraine"),
		array("AE","United Arab Emirates"),
		array("UK","United Kingdom (Great Britain)"),
		array("US","United States"),
		array("UY","Uruguay"),
		array("UM","US Minor Outlying Islands"),
		array("UZ","Uzbekistan"),
		array("VU","Vanuatu"),
		array("VA","Vatican City State (Holy See)"),
		array("VE","Venezuela"),
		array("VN","Viet Nam"),
		array("VG","Virgin Islands (British)"),
		array("VI","Virgin Islands (US)"),
		array("WF","Wallis and Futuna Islands"),
		array("EH","Western Sahara"),
		array("YE","Yemen"),
		array("YU","Yugoslavia"),
		array("ZR","Zaire"),
		array("ZM","Zambia"),
		array("ZW","Zimbabwe"),
		array("M","US Military Base"),
	);
	private $stateData = array(
		'US' => array(
			array("AK","Alaska"),
			array("AL","Alabama"),
			array("AR","Arkansas"),
			array("AZ","Arizona"),
			array("CA","California"),
			array("CO","Colorado"),
			array("CT","Connecticut"),
			array("DC","Washington, DC"),
			array("DE","Delaware"),
			array("FL","Florida"),
			array("GA","Georgia"),
			array("HI","Hawaii"),
			array("IA","Iowa"),
			array("ID","Idaho"),
			array("IL","Illinois"),
			array("IN","Indiana"),
			array("KS","Kansas"),
			array("KY","Kentucky"),
			array("LA","Louisiana"),
			array("MA","Massachusetts"),
			array("MD","Maryland"),
			array("ME","Maine"),
			array("MI","Michigan"),
			array("MN","Minnesota"),
			array("MO","Missouri"),
			array("MS","Mississippi"),
			array("MT","Montana"),
			array("NC","North Carolina"),
			array("ND","North Dakota"),
			array("NE","Nebraska"),
			array("NH","New Hampshire"),
			array("NJ","New Jersey"),
			array("NM","New Mexico"),
			array("NV","Nevada"),
			array("NY","New York"),
			array("OH","Ohio"),
			array("OK","Oklahoma"),
			array("OR","Oregon"),
			array("PA","Pennsylvania"),
			array("RI","Rhode Island"),
			array("SC","South Carolina"),
			array("SD","South Dakota"),
			array("TN","Tennessee"),
			array("TX","Texas"),
			array("UT","Utah"),
			array("VA","Virginia"),
			array("VT","Vermont"),
			array("WA","Washington"),
			array("WI","Wisconsin"),
			array("WV","West Virginia"),
			array("WY","Wyoming"),
		),
		'CA' => array(
			array("AB","Alberta"),
			array("BC","British Columbia"),
			array("MB","Manitoba"),
			array("NB","New Brunswick"),
			array("NF","Newfoundland"),
			array("NS","Nova Scotia"),
			array("NT","Northwest Territories"),
			array("NU","Nunavut"),
			array("ON","Ontario"),
			array("PE","Prince Edward Island"),
			array("PQ","Quebec"),
			array("SK","Saskatchewan"),
			array("YT","Yukon"),
		),
		'M' => array(
			array("AA","Armed Forces Americas"),
			array("AE","Armed Forces Europe"),
		)
	);

	private $timezoneData = array(
		array("1","America/Adak","","0.00"),
		array("2","America/Anchorage","","0.00"),
		array("3","America/Anguilla","","0.00"),
		array("4","America/Antigua","","0.00"),
		array("5","America/Araguaina","","0.00"),
		array("6","America/Argentina/Buenos_Aires","","-3.00"),
		array("7","America/Argentina/Catamarca","","0.00"),
		array("8","America/Argentina/ComodRivadavia","","0.00"),
		array("9","America/Argentina/Cordoba","","0.00"),
		array("10","America/Argentina/Jujuy","","0.00"),
		array("11","America/Argentina/La_Rioja","","0.00"),
		array("12","America/Argentina/Mendoza","","0.00"),
		array("13","America/Argentina/Rio_Gallegos","","0.00"),
		array("14","America/Argentina/Salta","","0.00"),
		array("15","America/Argentina/San_Juan","","0.00"),
		array("16","America/Argentina/San_Luis","","0.00"),
		array("17","America/Argentina/Tucuman","","0.00"),
		array("18","America/Argentina/Ushuaia","","0.00"),
		array("19","America/Aruba","","0.00"),
		array("20","America/Asuncion","","0.00"),
		array("21","America/Atikokan","","0.00"),
		array("22","America/Atka","","0.00"),
		array("23","America/Bahia","","0.00"),
		array("24","America/Barbados","","0.00"),
		array("25","America/Belem","","0.00"),
		array("26","America/Belize","","0.00"),
		array("27","America/Blanc-Sablon","","0.00"),
		array("28","America/Boa_Vista","","0.00"),
		array("29","America/Bogota","","0.00"),
		array("30","America/Boise","","0.00"),
		array("31","America/Buenos_Aires","","0.00"),
		array("32","America/Cambridge_Bay","","0.00"),
		array("33","America/Campo_Grande","","0.00"),
		array("34","America/Cancun","","0.00"),
		array("35","America/Caracas","","-4.00"),
		array("36","America/Catamarca","","0.00"),
		array("37","America/Cayenne","","0.00"),
		array("38","America/Cayman","","0.00"),
		array("39","America/Chicago","Central Time","-4.00"),
		array("40","America/Chihuahua","","0.00"),
		array("41","America/Coral_Harbour","","0.00"),
		array("42","America/Cordoba","","0.00"),
		array("43","America/Costa_Rica","","0.00"),
		array("44","America/Cuiaba","","0.00"),
		array("45","America/Curacao","","0.00"),
		array("46","America/Danmarkshavn","","0.00"),
		array("47","America/Dawson","","0.00"),
		array("48","America/Dawson_Creek","","0.00"),
		array("49","America/Denver","Mountain Time","-7.00"),
		array("50","America/Detroit","","0.00"),
		array("51","America/Dominica","","0.00"),
		array("52","America/Edmonton","","0.00"),
		array("53","America/Eirunepe","","0.00"),
		array("54","America/El_Salvador","","0.00"),
		array("55","America/Ensenada","","0.00"),
		array("56","America/Fort_Wayne","","0.00"),
		array("57","America/Fortaleza","","0.00"),
		array("58","America/Glace_Bay","","0.00"),
		array("59","America/Godthab","","0.00"),
		array("60","America/Goose_Bay","","0.00"),
		array("61","America/Grand_Turk","","0.00"),
		array("62","America/Grenada","","0.00"),
		array("63","America/Guadeloupe","","0.00"),
		array("64","America/Guatemala","","0.00"),
		array("65","America/Guayaquil","","0.00"),
		array("66","America/Guyana","","0.00"),
		array("67","America/Halifax","","0.00"),
		array("68","America/Havana","","0.00"),
		array("69","America/Hermosillo","","0.00"),
		array("70","America/Indiana/Indianapolis","","0.00"),
		array("71","America/Indiana/Knox","","0.00"),
		array("72","America/Indiana/Marengo","","0.00"),
		array("73","America/Indiana/Petersburg","","0.00"),
		array("74","America/Indiana/Tell_City","","0.00"),
		array("75","America/Indiana/Vevay","","0.00"),
		array("76","America/Indiana/Vincennes","","0.00"),
		array("77","America/Indiana/Winamac","","0.00"),
		array("78","America/Indianapolis","","0.00"),
		array("79","America/Inuvik","","0.00"),
		array("80","America/Iqaluit","","0.00"),
		array("81","America/Jamaica","","0.00"),
		array("82","America/Jujuy","","0.00"),
		array("83","America/Juneau","","-9.00"),
		array("84","America/Kentucky/Louisville","","0.00"),
		array("85","America/Kentucky/Monticello","","0.00"),
		array("86","America/Knox_IN","","0.00"),
		array("87","America/La_Paz","","0.00"),
		array("88","America/Lima","","0.00"),
		array("89","America/Los_Angeles","Pacific Time","-8.00"),
		array("90","America/Louisville","","0.00"),
		array("91","America/Maceio","","0.00"),
		array("92","America/Managua","","0.00"),
		array("93","America/Manaus","","0.00"),
		array("94","America/Marigot","","0.00"),
		array("95","America/Martinique","","0.00"),
		array("96","America/Matamoros","","0.00"),
		array("97","America/Mazatlan","","0.00"),
		array("98","America/Mendoza","","0.00"),
		array("99","America/Menominee","","0.00"),
		array("100","America/Merida","","0.00"),
		array("101","America/Mexico_City","","-6.00"),
		array("102","America/Miquelon","","0.00"),
		array("103","America/Moncton","","0.00"),
		array("104","America/Monterrey","","0.00"),
		array("105","America/Montevideo","","0.00"),
		array("106","America/Montreal","","0.00"),
		array("107","America/Montserrat","","0.00"),
		array("108","America/Nassau","","0.00"),
		array("109","America/New_York","Eastern Time","-5.00"),
		array("110","America/Nipigon","","0.00"),
		array("111","America/Nome","","0.00"),
		array("112","America/Noronha","","0.00"),
		array("113","America/North_Dakota/Center","","0.00"),
		array("114","America/North_Dakota/New_Salem","","0.00"),
		array("115","America/Ojinaga","","0.00"),
		array("116","America/Panama","","0.00"),
		array("117","America/Pangnirtung","","0.00"),
		array("118","America/Paramaribo","","0.00"),
		array("119","America/Phoenix","","0.00"),
		array("120","America/Port-au-Prince","","0.00"),
		array("121","America/Port_of_Spain","","0.00"),
		array("122","America/Porto_Acre","","0.00"),
		array("123","America/Porto_Velho","","0.00"),
		array("124","America/Puerto_Rico","","0.00"),
		array("125","America/Rainy_River","","0.00"),
		array("126","America/Rankin_Inlet","","0.00"),
		array("127","America/Recife","","0.00"),
		array("128","America/Regina","","0.00"),
		array("129","America/Resolute","","0.00"),
		array("130","America/Rio_Branco","","0.00"),
		array("131","America/Rosario","","0.00"),
		array("132","America/Santa_Isabel","","0.00"),
		array("133","America/Santarem","","0.00"),
		array("134","America/Santiago","","0.00"),
		array("135","America/Santo_Domingo","","0.00"),
		array("136","America/Sao_Paulo","","0.00"),
		array("137","America/Scoresbysund","","0.00"),
		array("138","America/Shiprock","","0.00"),
		array("139","America/St_Barthelemy","","0.00"),
		array("140","America/St_Johns","","-3.50"),
		array("141","America/St_Kitts","","0.00"),
		array("142","America/St_Lucia","","0.00"),
		array("143","America/St_Thomas","","0.00"),
		array("144","America/St_Vincent","","0.00"),
		array("145","America/Swift_Current","","0.00"),
		array("146","America/Tegucigalpa","","0.00"),
		array("147","America/Thule","","0.00"),
		array("148","America/Thunder_Bay","","0.00"),
		array("149","America/Tijuana","","0.00"),
		array("150","America/Toronto","","0.00"),
		array("151","America/Tortola","","0.00"),
		array("152","America/Vancouver","","0.00"),
		array("153","America/Virgin","","0.00"),
		array("154","America/Whitehorse","","0.00"),
		array("155","America/Winnipeg","","0.00"),
		array("156","America/Yakutat","","0.00"),
		array("157","America/Yellowknife","","0.00"),
	);

	public function before($event = array()) {
		$db = ConnectionManager::getDataSource($this->connection);
		$db->cacheSources = false;
		return true;
	}

	public function after($event = array()) {
		if (isset ($event['create'])) {
			switch ($event['create']) {
				case 'states':
					$this->insertStates();
				break;
				case 'countries':
					$this->insertCountries();
				break;
				case 'timezones':
					$this->insertTimezones();
				break;
			}
		}
	}

	public $countries = array(
		'id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'key' => 'primary', 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1)
		),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	public $states = array(
		'id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'key' => 'primary', 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'title' => array('type' => 'string', 'null' => false, 'default' => null, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'country_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 2, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'lat_min' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lat_max' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lon_min' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'lon_max' => array('type' => 'float', 'null' => false, 'default' => null, 'length' => '10,7'),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1)
		),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	public $timezones = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 8, 'key' => 'primary'),
		'title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 150, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'abbr' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 64, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
		'offset' => array('type' => float, 'null' => false, 'default' => '0.00', 'length' => '10,7'),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
		),
		'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM')
	);
	
	private function insertCountries() {
		$Country = ClassRegistry::init('Location.Country');
		$Country->create();
		$data = array();
		foreach ($this->countryData as $country) {
			list($id, $title) = $country;
			$data[] = compact(array('id', 'title'));
		}
		return $Country->saveAll($data);
	}
	
	private function insertStates() {
		$State = ClassRegistry::init('Location.State');
		$State->create();
		$data = array();
		foreach ($this->stateData as $country_id => $countryStates) {
			foreach ($countryStates as $state) {
				list($id, $title) = $state;
				$data[] = compact('country_id', 'id', 'title');
			}
		}
		return $State->saveAll($data);
	}
	
	private function insertTimezones() {
		$Timezone = ClassRegistry::init('Location.Timezone');
		$Timezone->create();
		$data = array();
		foreach ($this->timezoneData as $timezone) {
			list($id, $title, $abbr) = $timezone;
			$data[] = compact(array('id', 'title', 'abbr'));
		}
		return $Timezone->saveAll($data);
	}
}
